########################################################################
#
# Makefile     : cs2mcast
#
# Author       : Phil Maechling
#
# Last Revised : 2004/07/12
#
########################################################################

########################################################################
# Solaris 2 definitions
#
CXX	 = CC
CC	 = cc
CXXFLAGS = -I$(INCL) -DENDIAN_LITTLE
CFLAGS	 = -DENDIAN_LITTLE
LD	 = $(CXX)

INCL	 = ../../include
CSLIB	 = ../../util
LDLIBS	 = -L$(CSLIB) -lsocket -lnsl -lutil -lposix4
########################################################################

files = mcast.C cs2mcast.C

headers = RetCodes.h cdpstruc.h cpascal.h

cs2mcast = mcast.o cs2mcast.o

sources = $(headers) $(files)
objects = $(files:.C=.o)

program = cs2mcast

#implicit rules for converting C and c files to object files
#
.C.o:
	$(CXX) $(CXXFLAGS) -c $<

ALL = $(program)

$(program):$(objects) $(files)
	$(LD) $(cs2mcast) -o $@ $(LDLIBS) 


all: $(ALL)


clean:
	-rm -f *.o *~ core cs2mcast 

veryclean:
	-rm -f *.o *~ core cs2mcast 

install:
	cp -p cs2mcast ${BINDIR}
