########################################################################
#
# Makefile     : qmaserv main files
#
# Author       : Phil Maechling
#
# Last Revised : 2004/07/12
#
########################################################################

########################################################################
# Solaris 2 definitions
#
CXX	 = CC
CLIBDIR	 = /opt/SUNWspro/lib
DEBUG	 = -g
COPT	 = 
LDLIBS	 = -L../../util -lnsl -lsocket -lutil -lposix4 -R$(CLIBDIR)

CXXFLAGS = $(INCL) $(DEBUG) $(COPT)
LD	 = $(CXX)
INCL	 = -I../include -I../utils -I../msgs -I../qmaserv -I../cserv
LDFLAGS	 = $(DEBUG) $(LDLIBS)
########################################################################

files = ChanFreqMap.C ProcessMN232.C ProcessAG816.C ProcessMN816.C ProcessMN38.C ProcessAG38.C TypeChanFreqMap.C Q330Version.C ClockUtils.C Continuity.C StateInfoVO.C SplitSOD.C FrameUtils.C QueueDP.C CheckPCQS.C CheckLCQS.C ProcessDCMult.C ProcessDCComp.C ProcessDCD32.C ProcessIQ.C DetectorOptionsVO.C ClockProcVO.C NetStationVO.C SecondOfData.C CreatePacket.C OptionBitsVO.C Blockette.C LogTimingVO.C PCQ.C LCQ.C LCQVO.C ConfigInfoVO.C TokenBuffer.C TokenVO.C PacketMarker.C SlidingWindow.C AckCounter.C TimeServer.C ReceiveMsgs.C RxMsg.C SendCmds.C CountDownTimer.C TxCmd.C ReadConfig.C Verbose.C StateMachine.C ConfigVO.C QMA_Port.C Cleanup.C qmautils.C qmaserv.C 

headers = ChanFreqMap.h ProcessMN232.h ProcessAG816.h ProcessMN816.h ProcessMN38.h ProcessAG38.h TypeChanFreqMap.h Q330Version.h QMA_Version.h ClockUtils.h Continuity.h StateInfoVO.h SplitSOD.h FrameUtils.h QueueDP.h PacketQueue.h CheckPCQS.h CheckLCQS.h ProcessDCMult.h ProcessDCComp.h ProcessDCD32.h ProcessIQ.h DetectorOptionsVO.h ClockProcVO.h NetStationVO.h SecondOfData.h CreatePacket.h OptionBits.h Blockette.h LogTimingVO.h PCQ.h LCQ.h LCQVO.h ConfigInfoVO.h TokenBuffer.h TokenVO.h PacketMarker.h SlidingWindow.h AckCounter.h TimeServer.h BTI.h ReceiveMsgs.h RxMsg.h SendCmds.h CountDowntimer.h TxCmd.h ReadConfig.h Verbose.h StateMachine.C ConfigVO.h QMA_Port.h Cleanup.C qmautils.h qmaserv.h


cserv = ../cserv/buffers.o ../cserv/clink.o ../cserv/cmands.o ../cserv/cscfg.o ../cserv/cserv.o ../cserv/qmacfg.o
#
# Include this link statement if using comserv without linux routines
#cserv = ../cserv/buffers.o ../cserv/clink.o ../cserv/cmands.o ../cserv/cscfg.o ../cserv/cserv.o ../cserv/qmacfg.o ../cserv/linux.o


utils = ../utils/CharUtils.o ../utils/UnpackComp.o ../utils/CRC.o ../utils/findMD5.o ../utils/md5.o ../utils/ModuloCounter.o ../utils/TimeOfDay.o ../utils/SeqnoList.o ../utils/qmaswap.o ../utils/Logger.o

msgs = ../msgs/c1_umsg.o ../msgs/c1_stat.o ../msgs/c1_rqstat.o ../msgs/Field.o ../msgs/QDPHeader.o ../msgs/Packet.o ../msgs/PacketElement.o ../msgs/c1_mem.o ../msgs/c1_rqmem.o ../msgs/c1_cack.o ../msgs/c1_dsrv.o ../msgs/c1_rqsrv.o ../msgs/c1_srvch.o ../msgs/c1_srvrsp.o ../msgs/c1_rqflgs.o ../msgs/c1_flgs.o ../msgs/c1_cerr.o ../msgs/c1_log.o ../msgs/c1_sglob.o ../msgs/c1_fix.o ../msgs/c1_sc.o ../msgs/dt_open.o ../msgs/dt_data.o ../msgs/dt_fill.o ../msgs/dt_dack.o

sources = $(headers) $(files)
objects = $(files:.C=.o)

program =  qmaserv

#implicit rule for converting a C++ file to an object file
# C++ file is expected to have a .C suffix
.C.o:
	$(CXX) $(CXXFLAGS) -c $<

ALL =	$(program)

$(program):$(objects) $(files)
	$(LD) $(objects) $(utils) $(msgs) $(cserv) -o $@ $(LDFLAGS)

all:		$(ALL)

clean:
		-rm *.o qmaserv

veryclean:	clean
		-rm -f *~ qmaserv core

install:	
	cp qmaserv  $(BINDIR)
