########################################################################
#
# Makefile     : qserv utils files
#
# Author       : Phil Maechling
#
# Last Revised : 2004/07/12
#
########################################################################

########################################################################
# Solaris 2 definitions
#
CXX	 = g++
DEBUG	 = -g
COPT	 = 

INCL	 = -I../include -I../msgs -I../qmaserv
CXXFLAGS = -g $(INCL) $(COPT) $(DEBUG)
########################################################################

files = CharUtils.C SeqnoList.C UnpackComp.C CRC.C findMD5.C md5.C ModuloCounter.C TimeOfDay.C qmaswap.C Logger.C
headers = CharUtils.h SeqnoList.h UnpackComp.h DC.h CRC.h findMD5.h md5.h ModuloCounter.h TimeOfDay.h qmaswap.h Logger.h

sources = $(headers) $(files)
objects = $(files:.C=.o)

#implicit rule for converting a C++ file to an object file
# C++ file is expected to have a .C suffix
.C.o:
	$(CXX) $(CXXFLAGS) -c $<


ALL =		$(objects)

all:		$(ALL)

clean:
		-rm -f $(ALL)

veryclean:	clean
		-rm -f *~ 

install:	
	echo "install utils"
