#
# Simple makefile for the qmaserv process
# Phil Maechling
#
# Currently there is only a Makefile.linux target.
#
# Files of similiar types may be grouped into directories for
# convienence.
#
# The makefile in each directory should support the following targets:
#       all
#       clean
#       veryclean
#       install
#
BINDIR  = ../bin

ALL     = cserv lib330 qmaserv2 

all: 	
	for dir in $(ALL) ; do \
		echo build for $$dir ... ; \
		(cd $$dir; make -f Makefile.linux all); \
	done

clean:
	for dir in $(ALL) ; do \
		(cd $$dir; make -f Makefile.linux clean); \
	done

veryclean:
	for dir in $(ALL) ; do \
		(cd $$dir; make -f Makefile.linux veryclean); \
	done

install:
	for dir in qmaserv ; do \
		(cd $$dir; make -f Makefile.linux BINDIR=../$(BINDIR) install); \
	done
